In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.4'

## Create and Read

#### 1D array

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim # check the dimention of the array

1

In [8]:
arr1.size

5

#### 2D Array

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2.shape # (row,col)

(2, 3)

## Create Random Array

In [14]:
randomArr = np.random.rand(3, 2, 3) # 3 layers, 2 rows and 3 columns

In [16]:
randomArr

array([[[0.76445765, 0.2386558 , 0.80469313],
        [0.44689603, 0.74938201, 0.90471506]],

       [[0.00093421, 0.20198011, 0.84653537],
        [0.70621903, 0.34129399, 0.73105976]],

       [[0.7203679 , 0.05272045, 0.61491226],
        [0.83086241, 0.84084323, 0.86177015]]])

In [17]:
randomArr.dtype

dtype('float64')

In [18]:
zeros = np.zeros((3, 2, 3)) # Crete 3D array with value 0

In [19]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
full = np.full((3,2,3), 8) #Will create 3D array with value 8

In [21]:
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [22]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [23]:
randomArr[0]

array([[0.76445765, 0.2386558 , 0.80469313],
       [0.44689603, 0.74938201, 0.90471506]])

In [24]:
randomArr[0][0]

array([0.76445765, 0.2386558 , 0.80469313])

In [25]:
randomArr[0][0][0]

np.float64(0.7644576516197753)

In [26]:
randomArr[0:2]

array([[[0.76445765, 0.2386558 , 0.80469313],
        [0.44689603, 0.74938201, 0.90471506]],

       [[0.00093421, 0.20198011, 0.84653537],
        [0.70621903, 0.34129399, 0.73105976]]])

In [27]:
randomArr[1]

array([[0.00093421, 0.20198011, 0.84653537],
       [0.70621903, 0.34129399, 0.73105976]])

In [28]:
randomArr[1][0][1]

np.float64(0.20198010724603477)

In [29]:
randomArr[1,0,1]

np.float64(0.20198010724603477)